import requests
import os
import io
import pandas as pd
os.makedirs('data', exist_ok=True)
access_token = os.getenv('DW_TOKEN')

#3.6.1 Road traffic deaths World (EWs55)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_TRAF.1._T........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_6_1_Road_traffic_deaths_World_Total.csv', index=True)

#3.6.1 Road traffic deaths SDG regions (ybzj2)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_TRAF.53+62+513+543+747+753+202+419._T............/ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_6_1_Road_traffic_deaths_SDG_Regions.csv', index=True)

#3.6.1 Road traffic deaths Nordics OECD (bOwUi)
oecd_url='https://stats.oecd.org/SDMX-JSON/data/IRTAD_CASUAL_BY_AGE/DNK+FIN+ISL+NOR+SWE.KIL.TOT.TOT.RATE-POP-100T.CORRECTED/all?startTime=2000'
result = requests.get(oecd_url, headers={'Accept': 'text/csv'})
df=pd.read_csv(io.StringIO(result.text))
df_new = df.pivot(index='Country', columns='Year', values='Value')
df_new.to_csv('data/3_6_1_Road_Traffic_Deaths_Nordics.csv', index=True)

#3.7.1 Women Family Planning World (7ZvbI)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_FPL_MTMM.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_7_1_Women_Family_Planning_World_Total.csv', index=True)

#3.7.1 Women Family Planning SDG regions (V3T88)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_FPL_MTMM.53+62+513+543+747+753+202+419............../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_7_1_Women_Family_Planning_SDG_Regions.csv', index=True)

#3.7.1 Adolescent birth rate World (SLabG)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SP_DYN_ADKL.1..Y15T19........./ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_7_2_Adolescent_Birth_Rate_World_Total.csv', index=True)

#3.7.2 Adolescent Birth Rate SDG regions (uRSmS)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SP_DYN_ADKL.53+62+513+543+747+753+202+419..Y15T19........./ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_7_2_Adolescent_Birth_Rate_SDG_Regions.csv', index=True)

#3.7.2 Adolescent fertility rate OECD (jNvOV)
oecd_url='https://stats.oecd.org/SDMX-JSON/data/FAMILY/DNK+FIN+ISL+NOR+SWE.TOTAL.FAM20/all?startTime=2000'
result = requests.get(oecd_url, headers={'Accept': 'text/csv'})
df=pd.read_csv(io.StringIO(result.text))
df_new = df.pivot(index='Country', columns='Year', values='Value')
df_new.to_csv('data/3_7_2_Adolescent_Fertility_Rate_Nordics.csv', index=True)

#3.8.1 Universal Health Care Index World (DUq5f)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_UNHC.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_8_1_Universal_Health_Care_Index_World_Total.csv', index=True)

#3.8.1 Universal Health Care Index SDG regions (DUq5f)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_UNHC.53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_8_1_Universal_Health_Care_Index_SDG_Regions.csv', index=True)

#3.8.1 Universal Health Care Index Nordics (8JurX)
df_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_UNHC.208+246+352+578+752............../ALL/?detail=full&startPeriod=2000-01-01&dimensionAtObservation=TIME_PERIOD&format=csv")
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.to_csv('data/3_8_1_Universal_Health_Care_Index_Nordics.csv', index=True)

#3.8.2 Share Large Health Expenditure SDG regions (zgnG7)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_XPD_EARN10.1+53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={1: 'World', 53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America',543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_8_2_Share_Large_Health_Expenditure_SDG_Regions.csv', index=True)

#3.9.1 Mortality Household and air pollution SDG regions (tvmPS)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_ASAIRP.1+53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={1: 'World', 53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America',543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_9_1_Mortality_Household_Air_Pollution_SDG_Regions.csv', index=True)

#3.9.1 Household and air pollution Nordics (TrVi1)
df_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_ASAIRP.208+246+352+578+752............../ALL/?detail=full&startPeriod=2000-01-01&dimensionAtObservation=TIME_PERIOD&format=csv")
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.to_csv('data/3_9_1_Mortality_Household_Air_Pollution_Nordics.csv', index=True)

#3.9.2 WASH SDG regions (Ub8Mb)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_WASHARI.1+53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={1: 'World', 53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America',543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_9_2_Mortality_WASH_SDG_Regions.csv', index=True)

#3.9.2 WASH Nordics (xxxxx)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_WASHARI.208+246+352+578+752.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.to_csv('data/3_9_2_Mortality_WASH_Nordics.csv', index=True)

#3.9.3 Mortality unintentional posioning World (9k8OW)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_POISN.1._T........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_9_3_Mortality_Unintentional_Posioning_World_Total.csv', index=True)

#3.9.3 Mortality unintentional posioning SDG regions (VKShu)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_STA_POISN.53+62+513+543+747+753+202+419._T........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_9_3_Mortality_Unintentional_Posioning_SDG_Regions.csv', index=True)

#3.9.3 Mortality Accidental poisoning Nordics OECD (Au6rM)
oecd_url='https://stats.oecd.org/SDMX-JSON/data/HEALTH_STAT/CICDPOSN.TXCMILTX.DNK+FIN+ISL+NOR+SWE/all?startTime=2000'
result = requests.get(oecd_url, headers={'Accept': 'text/csv'})
df=pd.read_csv(io.StringIO(result.text))
df_new = df.pivot(index='Country', columns='Year', values='Value')
df_new.to_csv('data/3_9_3_Mortality_Accidental_Poisoning_Nordics.csv', index=True)

#3.a.1 Prevalence tobacco World (qSHFT)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_PRV_SMOK.1._T........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_a_1_Prevalence_Tobacco_World_Total.csv', index=True)

#3.a.1 Prevalence Tobacco SDG regions (yoBzM)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_PRV_SMOK.53+62+513+543+747+753+202+419._T........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_a_1_Prevalence_Tobacco_SDG_Regions.csv', index=True)

#3.a.1 Prevalence Tobacco Nordics (us4AE)
df_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_PRV_SMOK.208+246+352+578+752._T............/ALL/?detail=full&startPeriod=2000-01-01&dimensionAtObservation=TIME_PERIOD&format=csv")
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.to_csv('data/3_a_1_Prevalence_Tobacco_Nordics.csv', index=True)

#3.b.1 DTP3 World (UMgHK)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_DTP3.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_b_1_DTP3_World_Total.csv', index=True)

#3.b.1 MCV2 World (1vKaz)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_MCV2.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_b_1_MCV2_World_Total.csv', index=True)

#3.b.1 PCV3 World (8j9KU)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_PCV3.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_b_1_PCV3_World_Total.csv', index=True)

#3.b.1 HPV World (zhPGz)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_HPV.1.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World'}, inplace=True)
df_new.to_csv('data/3_b_1_HPV_World_Total.csv', index=True)

#3.b.1 DTP3 SDG regions (sBPJS)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_DTP3.53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_b_1_DTP3_SDG_Regions.csv', index=True)

#3.b.1 MCV2 SDG regions (4PrPX)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_MCV2.53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_b_1_MCV2_SDG_Regions.csv', index=True)

#3.b.1 PCV3 SDG regions (M1UgK)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_PCV3.53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_b_1_PCV3_SDG_Regions.csv', index=True)

#3.b.1 HPV SDG regions (yPNKH)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_HPV.53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='TIME_PERIOD', columns='REF_AREA', values='OBS_VALUE')
df_new.rename(columns={53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new.to_csv('data/3_b_1_HPV_SDG_Regions.csv', index=True)

#3.b.1 DTP3/MCV2/PCV3/HPV Nordics (hLWW4)
df_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_DTP3.208+246+352+578+752............./ALL/?detail=full&lastNObservations=1&format=csv")
df_new = df_csv.pivot(index='REF_AREA', columns='SERIES', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df2_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_MCV2.208+246+352+578+752............./ALL/?detail=full&lastNObservations=1&format=csv")
df2_new = df2_csv.pivot(index='REF_AREA', columns='SERIES', values='OBS_VALUE')
df2_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df3_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_PCV3.208+246+352+578+752............./ALL/?detail=full&lastNObservations=1&format=csv")
df3_new = df3_csv.pivot(index='REF_AREA', columns='SERIES', values='OBS_VALUE')
df3_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df4_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_ACS_HPV.208+246+352+578+752._T............/ALL/?detail=full&lastNObservations=1&format=csv")
df4_new = df4_csv.pivot(index='REF_AREA', columns='SERIES', values='OBS_VALUE')
df4_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_all = pd.concat([df_new,df2_new,df3_new,df4_new],axis=1)
df_all.to_csv('data/3_b_1_DTP3_MCV2_PCV3_HPV_Nordics.csv', index=True)

#3.b.2 Net ODA Health Total (0WKD3)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..DC_TOF_HLTHNT.515.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={515:'Total'}, inplace=True)
df_new.to_csv('data/3_b_2_Net_ODA_Health_Total.csv', index=True)

#3.c.1 Health Worker Density Total (Z4XdO)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_MED_DEN.1+9+150+15+21+30+34+35+143+145+202.........../ALL/?detail=full&lastNObservations=1&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='OCCUPATION', values='OBS_VALUE')
df_new.rename(index={1:'World',9:'Oceania',150:'Europe',15:'Northern Africa',21:'Northern America',30:'Eastern Asia',34:'Southern Asia',35:'South-Eastern Asia',143:'Central Asia',145:'Western Asia',202:'Sub-Saharan Africa' }, inplace=True)
df_new.rename(columns={'ISCO08_221':'Medical doctors','ISCO08_222_322':'Nursing and midwifery personnel', 'ISCO08_2261':'Dentists','ISCO08_2262':'Pharmacists'}, inplace=True)
df_new.to_csv('data/3_c_1_Health_Worker_Density_Total.csv', index=True)

#3.c.1 Health Worker Density Medical Doctors Nordics (dhEhe)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_MED_DEN.208+246+352+578+752......ISCO08_221...../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.rename(columns={'ISCO08_221':'Medical doctors','ISCO08_222_322':'Nursing and midwifery personnel', 'ISCO08_2261':'Dentists','ISCO08_2262':'Pharmacists'}, inplace=True)
df_new.to_csv('data/3_c_1_Health_Worker_Density_Medical_Doctors_Nordics.csv', index=True)

#3.c.1 Health Worker Density Nursing and midwifery personnel Nordics (INMP2)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_MED_DEN.208+246+352+578+752......ISCO08_222_322...../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.rename(columns={'ISCO08_221':'Medical doctors','ISCO08_222_322':'Nursing and midwifery personnel', 'ISCO08_2261':'Dentists','ISCO08_2262':'Pharmacists'}, inplace=True)
df_new.to_csv('data/3_c_1_Health_Worker_Density_Nursing_Midwifery_Nordics.csv', index=True)

#3.c.1 Health Worker Density Dentists Nordics (ILcaX)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_MED_DEN.208+246+352+578+752......ISCO08_2261...../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.rename(columns={'ISCO08_221':'Medical doctors','ISCO08_222_322':'Nursing and midwifery personnel', 'ISCO08_2261':'Dentists','ISCO08_2262':'Pharmacists'}, inplace=True)
df_new.to_csv('data/3_c_1_Health_Worker_Density_Dentists_Nordics.csv', index=True)

#3.c.1 Health Worker Density Pharmacists Nordics (dLEdy)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_MED_DEN.208+246+352+578+752......ISCO08_2262...../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new.rename(columns={'ISCO08_221':'Medical doctors','ISCO08_222_322':'Nursing and midwifery personnel', 'ISCO08_2261':'Dentists','ISCO08_2262':'Pharmacists'}, inplace=True)
df_new.to_csv('data/3_c_1_Health_Worker_Density_Pharmacists_Nordics.csv', index=True)

#3.d.1 IHR Capacity SDG regions (FoXOI)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_IHR_CAPS.1+53+62+513+543+747+753+202+419........SPAR2_C01+SPAR2_C02+SPAR2_C03+SPAR2_C04+SPAR2_C05+SPAR2_C06+SPAR2_C07+SPAR2_C08+SPAR2_C09+SPAR2_C10+SPAR2_C11+SPAR2_C12+SPAR2_C13+SPAR2_C14+SPAR2_C15.../ALL/?detail=full&lastNObservations=1&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='COMPOSITE_BREAKDOWN', values='OBS_VALUE')
df_new.rename(index={1: 'World', 53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'},inplace=True)
df_new['Average'] = df_new.mean(numeric_only=True, axis=1)
df_new.to_csv('data/3_d_1_IHR_SDG_Regions.csv', index=True)

#3.d.1 IHR Capacity Nordics (O4iVQ)
df_csv = pd.read_csv("https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_IHR_CAPS.208+246+352+578+752........SPAR2_C01+SPAR2_C02+SPAR2_C03+SPAR2_C04+SPAR2_C05+SPAR2_C06+SPAR2_C07+SPAR2_C08+SPAR2_C09+SPAR2_C10+SPAR2_C11+SPAR2_C12+SPAR2_C13+SPAR2_C14+SPAR2_C15.../ALL/?detail=full&lastNObservations=1&format=csv")
df_new = df_csv.pivot(index='REF_AREA', columns='COMPOSITE_BREAKDOWN', values='OBS_VALUE')
df_new.rename(index={208: 'Denmark', 246: 'Finland', 352: 'Iceland', 578:'Norway',752:'Sweden'},inplace=True)
df_new['Average'] = df_new.mean(numeric_only=True, axis=1)
df_new.to_csv('data/3_d_1_IHR_Nordics.csv', index=True)

#3.d.2 MRSA Total (f03pp)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_BLD_MRSA.1+53+62+513+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World',53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'}, inplace=True)
df_new.to_csv('data/3_d_2_MRSA_Total.csv', index=True)

#3.d.2 ECOLI World (HUWGr)
df_csv = pd.read_csv('https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.14/..SH_BLD_ECOLI.1+53+62+513+543+747+753+202+419.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD&format=csv')
df_new = df_csv.pivot(index='REF_AREA', columns='TIME_PERIOD', values='OBS_VALUE')
df_new.rename(index={1:'World',53: 'Australia and New Zealand', 62: 'Central and Southern Asia', 202: 'Sub-Saharan Africa', 419: 'Latin America and the Caribbean', 513: 'Europe and Northern America', 543: 'Oceania*', 747: 'Northern Africa and Western Asia', 753: 'Eastern and South-Eastern Asia'}, inplace=True)
df_new.to_csv('data/3_d_2_ECOLI_Total.csv', index=True)