name: SDG Data Update
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  setup:
    runs-on: Ubuntu-20.04
    steps:
      - name: Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: pip install -r requirements.txt

  update-sdg:
    needs: setup
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        sdg: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    steps:
      - name: Run SDG ${{ matrix.sdg }} Script
        env: 
          DW_TOKEN: ${{ secrets.DW_TOKEN }}
        run: python SDG_${{ matrix.sdg }}.py

  commit:
    needs: update-sdg
    runs-on: Ubuntu-20.04
    steps:
      - name: Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u +%Y-%m-%d-%H-%M-%S)
          branch_name="sdg-data-update-${timestamp}"
          git checkout -b "${branch_name}"
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push origin "${branch_name}"
